### ISSUE TITLE
unwrap?

### ISSUE THREAD

**Issue by mindplay-dk** [guardian/scribe-plugin-intelligent-unlink-command#10]
What are you calling here?

https://github.com/guardian/scribe-plugin-intelligent-unlink-command/blob/master/src/scribe-plugin-intelligent-unlink-command.js#L35

AFAIK, not a DOM Element method?

There's an unwrap function in `scribe/node`, maybe you meant to import that?

**Comment by rrees** [comment]
`scribe.element` see line 12

**Comment by mindplay-dk** [comment]
Oh, I see - it's exposing `scribe/node` - most other modules import it rather than accessing it that way... No worries :-)
